//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cancelyaria.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<decimal> MaxDiscount { get; set; }
        public string CurrentDiscounts { get; set; }
        public Nullable<int> StockAmount { get; set; }
        public string Description { get; set; }
        public byte[] ImagePath { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
